stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test 

build_image:
  stage: build
  image: docker:23.0.1
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWD
  script:
    - docker build -t charlied0cker/python-cicd-demo:python-app-1.0 .
    - docker push charlied0cker/python-cicd-demo:python-app-1.0

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@44.192.59.188 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASSWD && docker run -d -p 3000:3000 charlied0cker/python-cicd-demo:python-app-1.0" 